pipeline {
  // 전체 잡이 어떤 노드에서 실행될지?
  agent any

  parameters {
    // string(key: 'value', key: 'value')
    // booleanParam(name: 'name', defaultValue: true, description: 'desc')
    booleanParam(name: 'BUILD_DOCKER_IMAGE', defaultValue: true)
    booleanParam(name: 'RUN_TEST_CODE', defaultValue: true)
    booleanParam(name: 'PUSH_DOCKER_IMAGE', defaultValue: true)
    booleanParam(name: 'DEPLOY_WORKLOAD', defaultValue: true)

    // CI
    string(name: 'DOCKER_ACCOUNT_ID', defaultValue: 'minosmlee', description: 'Docker Account ID')
    string(name: 'DOCKER_IMAGE_NAME', defaultValue: 'simple-flask-app', description: 'Docker image name')
    string(name: 'DOCKER_IMAGE_TAG', defaultValue: 'v1', description: 'Docker image tag')

    // CD
    string(name: 'TARGET_SVR_USER', defaultValue: 'root', description: 'Target server user')
    string(name: 'TARGET_SVR_IP', defaultValue: '10.10.0.8', description: 'Target server IP')
    string(name: 'TARGET_SVR_PATH', defaultValue: '/root', description: 'Target server path')
  }

  environment {
    // key = 'value'
    DOCKER_IMAGE = "${params.DOCKER_ACCOUNT_ID}/${params.DOCKER_IMAGE_NAME}:${params.DOCKER_IMAGE_TAG}"
  }

  stages {
    stage('==== Build Docker Image ====') {
      // 특정 스테이지만 어떤 노드에서 실행될지??
      // agent {}
      when {
        expression { return params.BUILD_DOCKER_IMAGE }
      }
      steps {
        dir("${env.WORKSPACE}/pipeline") {
          sh'''
            docker build -t ${DOCKER_IMAGE} .
          '''
        }
      }
      post {
        always {
          echo 'Docker image build success'
        }
      }
    }
    stage('==== Run Test Code ====') {
      when {
        expression { return params.RUN_TEST_CODE }
      }
      steps {
        echo "Run test code"
      }
    }
    stage('==== Push Docker Image ====') {
      when {
        expression { return params.PUSH_DOCKER_IMAGE }
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub_jenkins', usernameVariable: 'DOCKER_ACCOUNT_ID', passwordVariable: 'DOCKER_ACCOUNT_PASSWORD')]) {
          sh """#!/bin/bash
            echo ${DOCKER_ACCOUNT_PASSWORD} | docker login -u ${DOCKER_ACCOUNT_ID} --password-stdin
            docker push ${DOCKER_IMAGE}
          """
        }
      }
      post {
        always {
          echo 'Docker image push success'
        }
      }
    }
    stage('==== Deploy Worksload ====') {
      when {
        expression { return params.DEPLOY_WORKLOAD }
      }
      steps {
        sshagent (credentials: ['app-server']) {
          sh """#!/bin/bash

            scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
              pipeline/docker-compose.yml \
              ${params.TARGET_SVR_USER}@${params.TARGET_SVR_IP}:${params.TARGET_SVR_PATH}
            
            ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
              ${params.TARGET_SVR_USER}@${params.TARGET_SVR_IP} \
              \"export IMAGE=${DOCKER_IMAGE}; \
               docker-compose -f docker-compose.yml down; \
               docker-compose -f docker-compose.yml up -d\"

          """
        }
      }
    }
  }
  
  post {
    cleanup {
      sh('docker image prune -f')
      sh('docker container prune -f')
    }
    success {
      slackSend(
        channel: "#jenkins",
        color: "good",
        message: "[Jenkins Pipeline Success] Job: ${env.JOB_NAME}, Build Num: ${env.BUILD_NUMBER}. (${env.RUN_DISPLAY_URL} | open job detail)"
      )
    }
    failure {
      slackSend(
        channel: "#jenkins",
        color: "danger",
        message: "[Jenkins Pipeline Failure] Job: ${env.JOB_NAME}, Build Num: ${env.BUILD_NUMBER}. (${env.RUN_DISPLAY_URL} | open job detail)"
      )
    }
  }

}