pipeline {
  // 전체 잡이 어떤 노드에서 실행될지?
  agent any

  parameters {
    // string(key: 'value', key: 'value')
    // booleanParam(name: 'name', defaultValue: true, description: 'desc')
    booleanParam(name: 'BUILD_DOCKER_IMAGE', defaultValue: true)
    booleanParam(name: 'RUN_TEST_CODE', defaultValue: true)
    booleanParam(name: 'PUSH_DOCKER_IMAGE', defaultValue: true)
    booleanParam(name: 'DEPLOY_WORKLOAD', defaultValue: true)

    // CI
    string(name: 'DOCKER_ACCOUNT_ID', defaultValue: 'minosmlee', description: 'Docker Account ID')
    string(name: 'DOCKER_IMAGE_NAME', defaultValue: 'simple-flask-app', description: 'Docker image name')
    string(name: 'DOCKER_IMAGE_TAG', defaultValue: 'v1', description: 'Docker image tag')

    // CD
    string(name: 'TARGET_SVR_USER', defaultValue: 'ec2-user', description: 'Target server user')
    string(name: 'TARGET_SVR_IP', defaultValue: '10.0.3.163', description: 'Target server IP')
    string(name: 'TARGET_SVR_PATH', defaultValue: '/home/ec2-user', description: 'Target server path')
  }

  environment {
    // key = 'value'
    DOCKER_IMAGE = "${params.DOCKER_ACCOUNT_ID}/${params.DOCKER_IMAGE_NAME}:${params.DOCKER_IMAGE_TAG}"
  }

  stages {
    stage('==== Build Docker Image ====') {
      // 특정 스테이지만 어떤 노드에서 실행될지??
      // agent {}
      when {
        expression { return params.BUILD_DOCKER_IMAGE }
      }
      steps {
        dir("${env.WORKSPACE}/pipeline") {
          sh'''
            docker build -t ${DOCKER_IMAGE} .
          '''
        }
      }
      post {
        always {
          echo 'Docker image build success'
        }
      }
    }
    stage('==== Run Test Code ====') {
      when {
        expression { return params.RUN_TEST_CODE }
      }
      steps {
        echo "Run test code"
      }
    }
    stage('==== Push Docker Image ====') {
      when {
        expression { return params.PUSH_DOCKER_IMAGE }
      }
      steps {
        script{
          env.DOCKER_ACCOUNT_PASSWORD = input message: "Enter the password for Docker Hub "
        }
        sh """
          echo ${DOCKER_ACCOUNT_PASSWORD} | docker login -u ${params.DOCKER_ACCOUNT_ID} --password-stdin
        """
      }
      post {
        always {
          echo 'Docker image push success'
        }
      }
    }
    stage('==== Deploy Worksload ====') {
      when {
        expression { return params.DEPLOY_WORKLOAD }
      }
      steps {
        echo "Deploy workload"
        // sshagent (credentials: ['aws_ssh']) {
        //   sh'''
        //     #!/bin/bash

        //     scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
        //       deploy/docker-compose.yml \
        //       ${params.TARGET_SVR_USER}@${params.TARGET_SVR_IP}:${params.TARGET_SVR_PATH}
            
        //     ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
        //       ${params.TARGET_SVR_USER}@${params.TARGET_SVR_IP} \
        //       "aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}; \
        //        export IMAGE=${params.DOCKER_IMAGE_NAME}; \
        //        export TAG=${params.DOCKER_IMAGE_TAG}; \
        //        docker-compose -f docker-compose.yml down; \
        //        docker-compose -f docker-compose.yml up -d"

        //   '''
        // }
      }
    }
  }
  
  post {
    cleanup {
      sh('docker image prune -f')
      sh('docker container prune -f')
    }
  }

}